/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    customers: Customer;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('pl' | 'en') | ('pl' | 'en')[];
  globals: {
    site: Site;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
  };
  locale: 'pl' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  addresses?:
    | {
        line1: string;
        line2?: string | null;
        city: string;
        postalCode: string;
        country: string;
        id?: string | null;
      }[]
    | null;
  marketingConsent?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  email?: T;
  firstName?: T;
  lastName?: T;
  addresses?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        postalCode?: T;
        country?: T;
        id?: T;
      };
  marketingConsent?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  hero_tagline?: string | null;
  hero_heading_lines?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  hero_lead?: string | null;
  hero_ctas?:
    | {
        label?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  about_eyebrow?: string | null;
  about_heading_lines?:
    | {
        text: string;
        color: 'off-black' | 'coral' | 'blue' | 'white' | 'pink' | 'yellow';
        id?: string | null;
      }[]
    | null;
  about_intro?: string | null;
  about_quote?: string | null;
  about_paragraphs?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  about_image_alt?: string | null;
  about_image?: (number | null) | Media;
  services_eyebrow?: string | null;
  services_background_alt?: string | null;
  services_background?: (number | null) | Media;
  services_slides?:
    | {
        title?: string | null;
        tagline?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  camp_food_eyebrow?: string | null;
  camp_food_kicker?: string | null;
  camp_food_heading_lines?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  camp_food_cta?: {
    label?: string | null;
    href?: string | null;
  };
  camp_food_slides?:
    | {
        alt?: string | null;
        description?: string | null;
        image?: (number | null) | Media;
        theme: 'orange' | 'blue';
        image_orientation: 'vertical' | 'horizontal';
        id?: string | null;
      }[]
    | null;
  gallery_eyebrow?: string | null;
  gallery_heading?: string | null;
  gallery_handle?: string | null;
  gallery_images?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  contact_eyebrow?: string | null;
  contact_heading_lines?:
    | {
        text: string;
        color: 'off-black' | 'coral' | 'blue' | 'white' | 'pink' | 'yellow';
        id?: string | null;
      }[]
    | null;
  contact_lead?: string | null;
  contact_description?: string | null;
  contact_email?: {
    label?: string | null;
    value?: string | null;
    href?: string | null;
  };
  contact_instagram?: {
    label?: string | null;
    value?: string | null;
    href?: string | null;
  };
  contact_form_placeholder?: string | null;
  contact_submit?: {
    label?: string | null;
    href?: string | null;
  };
  contact_footer?: string | null;
  site_title?: string | null;
  site_description?: string | null;
  nav_items?:
    | {
        label?: string | null;
        section_id?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  hero_tagline?: T;
  hero_heading_lines?:
    | T
    | {
        text?: T;
        id?: T;
      };
  hero_lead?: T;
  hero_ctas?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  about_eyebrow?: T;
  about_heading_lines?:
    | T
    | {
        text?: T;
        color?: T;
        id?: T;
      };
  about_intro?: T;
  about_quote?: T;
  about_paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  about_image_alt?: T;
  about_image?: T;
  services_eyebrow?: T;
  services_background_alt?: T;
  services_background?: T;
  services_slides?:
    | T
    | {
        title?: T;
        tagline?: T;
        description?: T;
        id?: T;
      };
  camp_food_eyebrow?: T;
  camp_food_kicker?: T;
  camp_food_heading_lines?:
    | T
    | {
        text?: T;
        id?: T;
      };
  camp_food_cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  camp_food_slides?:
    | T
    | {
        alt?: T;
        description?: T;
        image?: T;
        theme?: T;
        image_orientation?: T;
        id?: T;
      };
  gallery_eyebrow?: T;
  gallery_heading?: T;
  gallery_handle?: T;
  gallery_images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  contact_eyebrow?: T;
  contact_heading_lines?:
    | T
    | {
        text?: T;
        color?: T;
        id?: T;
      };
  contact_lead?: T;
  contact_description?: T;
  contact_email?:
    | T
    | {
        label?: T;
        value?: T;
        href?: T;
      };
  contact_instagram?:
    | T
    | {
        label?: T;
        value?: T;
        href?: T;
      };
  contact_form_placeholder?: T;
  contact_submit?:
    | T
    | {
        label?: T;
        href?: T;
      };
  contact_footer?: T;
  site_title?: T;
  site_description?: T;
  nav_items?:
    | T
    | {
        label?: T;
        section_id?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}